# Generated by Django 3.1.2 on 2021-03-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourse',
            name='content',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
