# Generated by Django 3.1.2 on 2021-01-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210128_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogreadnum',
            old_name='readed_num',
            new_name='read_num',
        ),
    ]
