# Generated by Django 3.1.2 on 2021-01-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210128_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreadnum',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blog'),
        ),
    ]
