# Generated by Django 3.1.2 on 2021-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210128_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogReadNum',
        ),
    ]
