# Generated by Django 3.1.2 on 2021-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210219_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, upload_to='blog_avater/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='urls',
            field=models.URLField(default='#'),
        ),
    ]
