# Generated by Django 3.1.2 on 2021-03-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blog'),
        ),
    ]
