# Generated by Django 3.1.2 on 2021-03-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210308_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
