# Generated by Django 3.1.2 on 2021-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
