# Generated by Django 3.1.2 on 2021-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_health_form', '0002_auto_20210321_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
