# Generated by Django 3.1.2 on 2021-02-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210208_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='auth',
            new_name='user',
        ),
    ]
